/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AArrayOtypeSpec extends POtypeSpec
{
    private POtypeSpec _otypeSpec_;

    public AArrayOtypeSpec()
    {
        // Constructor
    }

    public AArrayOtypeSpec(
        @SuppressWarnings("hiding") POtypeSpec _otypeSpec_)
    {
        // Constructor
        setOtypeSpec(_otypeSpec_);

    }

    @Override
    public Object clone()
    {
        return new AArrayOtypeSpec(
            cloneNode(this._otypeSpec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayOtypeSpec(this);
    }

    public POtypeSpec getOtypeSpec()
    {
        return this._otypeSpec_;
    }

    public void setOtypeSpec(POtypeSpec node)
    {
        if(this._otypeSpec_ != null)
        {
            this._otypeSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otypeSpec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otypeSpec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otypeSpec_ == child)
        {
            this._otypeSpec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otypeSpec_ == oldChild)
        {
            setOtypeSpec((POtypeSpec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
