/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionOnamespaceElt extends POnamespaceElt
{
    private POfunctionDeclaration _ofunctionDeclaration_;

    public AFunctionOnamespaceElt()
    {
        // Constructor
    }

    public AFunctionOnamespaceElt(
        @SuppressWarnings("hiding") POfunctionDeclaration _ofunctionDeclaration_)
    {
        // Constructor
        setOfunctionDeclaration(_ofunctionDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionOnamespaceElt(
            cloneNode(this._ofunctionDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionOnamespaceElt(this);
    }

    public POfunctionDeclaration getOfunctionDeclaration()
    {
        return this._ofunctionDeclaration_;
    }

    public void setOfunctionDeclaration(POfunctionDeclaration node)
    {
        if(this._ofunctionDeclaration_ != null)
        {
            this._ofunctionDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ofunctionDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ofunctionDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ofunctionDeclaration_ == child)
        {
            this._ofunctionDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ofunctionDeclaration_ == oldChild)
        {
            setOfunctionDeclaration((POfunctionDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
