/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import java.util.*;
import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AIfErrorOprocStmt extends POprocStmt
{
    private final LinkedList<POprocStmt> _oprocStmt_ = new LinkedList<POprocStmt>();

    public AIfErrorOprocStmt()
    {
        // Constructor
    }

    public AIfErrorOprocStmt(
        @SuppressWarnings("hiding") List<?> _oprocStmt_)
    {
        // Constructor
        setOprocStmt(_oprocStmt_);

    }

    @Override
    public Object clone()
    {
        return new AIfErrorOprocStmt(
            cloneList(this._oprocStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfErrorOprocStmt(this);
    }

    public LinkedList<POprocStmt> getOprocStmt()
    {
        return this._oprocStmt_;
    }

    public void setOprocStmt(List<?> list)
    {
        for(POprocStmt e : this._oprocStmt_)
        {
            e.parent(null);
        }
        this._oprocStmt_.clear();

        for(Object obj_e : list)
        {
            POprocStmt e = (POprocStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._oprocStmt_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oprocStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oprocStmt_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<POprocStmt> i = this._oprocStmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((POprocStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
