/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AInlineOartifactSpec extends POartifactSpec
{
    private POartifactSet _oartifactSet_;

    public AInlineOartifactSpec()
    {
        // Constructor
    }

    public AInlineOartifactSpec(
        @SuppressWarnings("hiding") POartifactSet _oartifactSet_)
    {
        // Constructor
        setOartifactSet(_oartifactSet_);

    }

    @Override
    public Object clone()
    {
        return new AInlineOartifactSpec(
            cloneNode(this._oartifactSet_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInlineOartifactSpec(this);
    }

    public POartifactSet getOartifactSet()
    {
        return this._oartifactSet_;
    }

    public void setOartifactSet(POartifactSet node)
    {
        if(this._oartifactSet_ != null)
        {
            this._oartifactSet_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oartifactSet_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oartifactSet_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oartifactSet_ == child)
        {
            this._oartifactSet_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oartifactSet_ == oldChild)
        {
            setOartifactSet((POartifactSet) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
