/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ALiteralOexpr extends POexpr
{
    private POliteral _oliteral_;

    public ALiteralOexpr()
    {
        // Constructor
    }

    public ALiteralOexpr(
        @SuppressWarnings("hiding") POliteral _oliteral_)
    {
        // Constructor
        setOliteral(_oliteral_);

    }

    @Override
    public Object clone()
    {
        return new ALiteralOexpr(
            cloneNode(this._oliteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALiteralOexpr(this);
    }

    public POliteral getOliteral()
    {
        return this._oliteral_;
    }

    public void setOliteral(POliteral node)
    {
        if(this._oliteral_ != null)
        {
            this._oliteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oliteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oliteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oliteral_ == child)
        {
            this._oliteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oliteral_ == oldChild)
        {
            setOliteral((POliteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
