/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import java.util.*;
import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ALocalOartifactSet extends POartifactSet
{
    private final LinkedList<POfilesetOperation> _ofilesetOperation_ = new LinkedList<POfilesetOperation>();

    public ALocalOartifactSet()
    {
        // Constructor
    }

    public ALocalOartifactSet(
        @SuppressWarnings("hiding") List<?> _ofilesetOperation_)
    {
        // Constructor
        setOfilesetOperation(_ofilesetOperation_);

    }

    @Override
    public Object clone()
    {
        return new ALocalOartifactSet(
            cloneList(this._ofilesetOperation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALocalOartifactSet(this);
    }

    public LinkedList<POfilesetOperation> getOfilesetOperation()
    {
        return this._ofilesetOperation_;
    }

    public void setOfilesetOperation(List<?> list)
    {
        for(POfilesetOperation e : this._ofilesetOperation_)
        {
            e.parent(null);
        }
        this._ofilesetOperation_.clear();

        for(Object obj_e : list)
        {
            POfilesetOperation e = (POfilesetOperation) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._ofilesetOperation_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ofilesetOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ofilesetOperation_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<POfilesetOperation> i = this._ofilesetOperation_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((POfilesetOperation) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
