/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ALogicOliteral extends POliteral
{
    private POlogicLiteral _ologicLiteral_;

    public ALogicOliteral()
    {
        // Constructor
    }

    public ALogicOliteral(
        @SuppressWarnings("hiding") POlogicLiteral _ologicLiteral_)
    {
        // Constructor
        setOlogicLiteral(_ologicLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ALogicOliteral(
            cloneNode(this._ologicLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicOliteral(this);
    }

    public POlogicLiteral getOlogicLiteral()
    {
        return this._ologicLiteral_;
    }

    public void setOlogicLiteral(POlogicLiteral node)
    {
        if(this._ologicLiteral_ != null)
        {
            this._ologicLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ologicLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ologicLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ologicLiteral_ == child)
        {
            this._ologicLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ologicLiteral_ == oldChild)
        {
            setOlogicLiteral((POlogicLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
