/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ANewerThanOageExpr extends POageExpr
{
    private POidRef _newerId_;
    private POidRef _olderId_;

    public ANewerThanOageExpr()
    {
        // Constructor
    }

    public ANewerThanOageExpr(
        @SuppressWarnings("hiding") POidRef _newerId_,
        @SuppressWarnings("hiding") POidRef _olderId_)
    {
        // Constructor
        setNewerId(_newerId_);

        setOlderId(_olderId_);

    }

    @Override
    public Object clone()
    {
        return new ANewerThanOageExpr(
            cloneNode(this._newerId_),
            cloneNode(this._olderId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewerThanOageExpr(this);
    }

    public POidRef getNewerId()
    {
        return this._newerId_;
    }

    public void setNewerId(POidRef node)
    {
        if(this._newerId_ != null)
        {
            this._newerId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newerId_ = node;
    }

    public POidRef getOlderId()
    {
        return this._olderId_;
    }

    public void setOlderId(POidRef node)
    {
        if(this._olderId_ != null)
        {
            this._olderId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._olderId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._newerId_)
            + toString(this._olderId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._newerId_ == child)
        {
            this._newerId_ = null;
            return;
        }

        if(this._olderId_ == child)
        {
            this._olderId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._newerId_ == oldChild)
        {
            setNewerId((POidRef) newChild);
            return;
        }

        if(this._olderId_ == oldChild)
        {
            setOlderId((POidRef) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
