/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AOvariable extends POvariable
{
    private POidRef _oidRef_;

    public AOvariable()
    {
        // Constructor
    }

    public AOvariable(
        @SuppressWarnings("hiding") POidRef _oidRef_)
    {
        // Constructor
        setOidRef(_oidRef_);

    }

    @Override
    public Object clone()
    {
        return new AOvariable(
            cloneNode(this._oidRef_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOvariable(this);
    }

    public POidRef getOidRef()
    {
        return this._oidRef_;
    }

    public void setOidRef(POidRef node)
    {
        if(this._oidRef_ != null)
        {
            this._oidRef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oidRef_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oidRef_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oidRef_ == child)
        {
            this._oidRef_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oidRef_ == oldChild)
        {
            setOidRef((POidRef) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
