/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class APrepositionOtypeSpecSeparator extends POtypeSpecSeparator
{
    private POpreposition _opreposition_;

    public APrepositionOtypeSpecSeparator()
    {
        // Constructor
    }

    public APrepositionOtypeSpecSeparator(
        @SuppressWarnings("hiding") POpreposition _opreposition_)
    {
        // Constructor
        setOpreposition(_opreposition_);

    }

    @Override
    public Object clone()
    {
        return new APrepositionOtypeSpecSeparator(
            cloneNode(this._opreposition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrepositionOtypeSpecSeparator(this);
    }

    public POpreposition getOpreposition()
    {
        return this._opreposition_;
    }

    public void setOpreposition(POpreposition node)
    {
        if(this._opreposition_ != null)
        {
            this._opreposition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opreposition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opreposition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opreposition_ == child)
        {
            this._opreposition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opreposition_ == oldChild)
        {
            setOpreposition((POpreposition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
