/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ARangeOrangeSpec extends POrangeSpec
{
    private TWholeNumber _from_;
    private TWholeNumber _to_;

    public ARangeOrangeSpec()
    {
        // Constructor
    }

    public ARangeOrangeSpec(
        @SuppressWarnings("hiding") TWholeNumber _from_,
        @SuppressWarnings("hiding") TWholeNumber _to_)
    {
        // Constructor
        setFrom(_from_);

        setTo(_to_);

    }

    @Override
    public Object clone()
    {
        return new ARangeOrangeSpec(
            cloneNode(this._from_),
            cloneNode(this._to_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARangeOrangeSpec(this);
    }

    public TWholeNumber getFrom()
    {
        return this._from_;
    }

    public void setFrom(TWholeNumber node)
    {
        if(this._from_ != null)
        {
            this._from_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._from_ = node;
    }

    public TWholeNumber getTo()
    {
        return this._to_;
    }

    public void setTo(TWholeNumber node)
    {
        if(this._to_ != null)
        {
            this._to_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._to_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._from_)
            + toString(this._to_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._from_ == child)
        {
            this._from_ = null;
            return;
        }

        if(this._to_ == child)
        {
            this._to_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._from_ == oldChild)
        {
            setFrom((TWholeNumber) newChild);
            return;
        }

        if(this._to_ == oldChild)
        {
            setTo((TWholeNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
