/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ARepoOnamespaceElt extends POnamespaceElt
{
    private POrepoDeclaration _orepoDeclaration_;

    public ARepoOnamespaceElt()
    {
        // Constructor
    }

    public ARepoOnamespaceElt(
        @SuppressWarnings("hiding") POrepoDeclaration _orepoDeclaration_)
    {
        // Constructor
        setOrepoDeclaration(_orepoDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ARepoOnamespaceElt(
            cloneNode(this._orepoDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepoOnamespaceElt(this);
    }

    public POrepoDeclaration getOrepoDeclaration()
    {
        return this._orepoDeclaration_;
    }

    public void setOrepoDeclaration(POrepoDeclaration node)
    {
        if(this._orepoDeclaration_ != null)
        {
            this._orepoDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orepoDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._orepoDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._orepoDeclaration_ == child)
        {
            this._orepoDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._orepoDeclaration_ == oldChild)
        {
            setOrepoDeclaration((POrepoDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
