/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ASeparatorOtypeSpec extends POtypeSpec
{
    private POtypeSpecSeparator _otypeSpecSeparator_;

    public ASeparatorOtypeSpec()
    {
        // Constructor
    }

    public ASeparatorOtypeSpec(
        @SuppressWarnings("hiding") POtypeSpecSeparator _otypeSpecSeparator_)
    {
        // Constructor
        setOtypeSpecSeparator(_otypeSpecSeparator_);

    }

    @Override
    public Object clone()
    {
        return new ASeparatorOtypeSpec(
            cloneNode(this._otypeSpecSeparator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeparatorOtypeSpec(this);
    }

    public POtypeSpecSeparator getOtypeSpecSeparator()
    {
        return this._otypeSpecSeparator_;
    }

    public void setOtypeSpecSeparator(POtypeSpecSeparator node)
    {
        if(this._otypeSpecSeparator_ != null)
        {
            this._otypeSpecSeparator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otypeSpecSeparator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otypeSpecSeparator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otypeSpecSeparator_ == child)
        {
            this._otypeSpecSeparator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otypeSpecSeparator_ == oldChild)
        {
            setOtypeSpecSeparator((POtypeSpecSeparator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
