/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ASpecifiedOstringValueOpt extends POstringValueOpt
{
    private POstringLiteral _ostringLiteral_;

    public ASpecifiedOstringValueOpt()
    {
        // Constructor
    }

    public ASpecifiedOstringValueOpt(
        @SuppressWarnings("hiding") POstringLiteral _ostringLiteral_)
    {
        // Constructor
        setOstringLiteral(_ostringLiteral_);

    }

    @Override
    public Object clone()
    {
        return new ASpecifiedOstringValueOpt(
            cloneNode(this._ostringLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASpecifiedOstringValueOpt(this);
    }

    public POstringLiteral getOstringLiteral()
    {
        return this._ostringLiteral_;
    }

    public void setOstringLiteral(POstringLiteral node)
    {
        if(this._ostringLiteral_ != null)
        {
            this._ostringLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ostringLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ostringLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ostringLiteral_ == child)
        {
            this._ostringLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ostringLiteral_ == oldChild)
        {
            setOstringLiteral((POstringLiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
