/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AString2OstringLiteral extends POstringLiteral
{
    private TString2 _string2_;

    public AString2OstringLiteral()
    {
        // Constructor
    }

    public AString2OstringLiteral(
        @SuppressWarnings("hiding") TString2 _string2_)
    {
        // Constructor
        setString2(_string2_);

    }

    @Override
    public Object clone()
    {
        return new AString2OstringLiteral(
            cloneNode(this._string2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAString2OstringLiteral(this);
    }

    public TString2 getString2()
    {
        return this._string2_;
    }

    public void setString2(TString2 node)
    {
        if(this._string2_ != null)
        {
            this._string2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._string2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._string2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._string2_ == child)
        {
            this._string2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._string2_ == oldChild)
        {
            setString2((TString2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
