/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ASuccessOexpr extends POexpr
{
    private POsuccessExpr _osuccessExpr_;

    public ASuccessOexpr()
    {
        // Constructor
    }

    public ASuccessOexpr(
        @SuppressWarnings("hiding") POsuccessExpr _osuccessExpr_)
    {
        // Constructor
        setOsuccessExpr(_osuccessExpr_);

    }

    @Override
    public Object clone()
    {
        return new ASuccessOexpr(
            cloneNode(this._osuccessExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuccessOexpr(this);
    }

    public POsuccessExpr getOsuccessExpr()
    {
        return this._osuccessExpr_;
    }

    public void setOsuccessExpr(POsuccessExpr node)
    {
        if(this._osuccessExpr_ != null)
        {
            this._osuccessExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._osuccessExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._osuccessExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._osuccessExpr_ == child)
        {
            this._osuccessExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._osuccessExpr_ == oldChild)
        {
            setOsuccessExpr((POsuccessExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
