/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class ATaskOnamespaceElt extends POnamespaceElt
{
    private POtaskDeclaration _otaskDeclaration_;

    public ATaskOnamespaceElt()
    {
        // Constructor
    }

    public ATaskOnamespaceElt(
        @SuppressWarnings("hiding") POtaskDeclaration _otaskDeclaration_)
    {
        // Constructor
        setOtaskDeclaration(_otaskDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new ATaskOnamespaceElt(
            cloneNode(this._otaskDeclaration_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATaskOnamespaceElt(this);
    }

    public POtaskDeclaration getOtaskDeclaration()
    {
        return this._otaskDeclaration_;
    }

    public void setOtaskDeclaration(POtaskDeclaration node)
    {
        if(this._otaskDeclaration_ != null)
        {
            this._otaskDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otaskDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otaskDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otaskDeclaration_ == child)
        {
            this._otaskDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otaskDeclaration_ == oldChild)
        {
            setOtaskDeclaration((POtaskDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
