/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AVariableOexpr extends POexpr
{
    private POvariable _ovariable_;

    public AVariableOexpr()
    {
        // Constructor
    }

    public AVariableOexpr(
        @SuppressWarnings("hiding") POvariable _ovariable_)
    {
        // Constructor
        setOvariable(_ovariable_);

    }

    @Override
    public Object clone()
    {
        return new AVariableOexpr(
            cloneNode(this._ovariable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableOexpr(this);
    }

    public POvariable getOvariable()
    {
        return this._ovariable_;
    }

    public void setOvariable(POvariable node)
    {
        if(this._ovariable_ != null)
        {
            this._ovariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ovariable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ovariable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ovariable_ == child)
        {
            this._ovariable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ovariable_ == oldChild)
        {
            setOvariable((POvariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
