/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import java.util.*;
import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class AVersionOfilePreference extends POfilePreference
{
    private final LinkedList<POrangeSpec> _orangeSpec_ = new LinkedList<POrangeSpec>();

    public AVersionOfilePreference()
    {
        // Constructor
    }

    public AVersionOfilePreference(
        @SuppressWarnings("hiding") List<?> _orangeSpec_)
    {
        // Constructor
        setOrangeSpec(_orangeSpec_);

    }

    @Override
    public Object clone()
    {
        return new AVersionOfilePreference(
            cloneList(this._orangeSpec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVersionOfilePreference(this);
    }

    public LinkedList<POrangeSpec> getOrangeSpec()
    {
        return this._orangeSpec_;
    }

    public void setOrangeSpec(List<?> list)
    {
        for(POrangeSpec e : this._orangeSpec_)
        {
            e.parent(null);
        }
        this._orangeSpec_.clear();

        for(Object obj_e : list)
        {
            POrangeSpec e = (POrangeSpec) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._orangeSpec_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._orangeSpec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._orangeSpec_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<POrangeSpec> i = this._orangeSpec_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((POrangeSpec) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
