/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TArtifact extends Token
{
    public TArtifact()
    {
        super.setText("artifact");
    }

    public TArtifact(int line, int pos)
    {
        super.setText("artifact");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArtifact(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArtifact(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArtifact text.");
    }
}
