/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TBinds extends Token
{
    public TBinds()
    {
        super.setText("binds");
    }

    public TBinds(int line, int pos)
    {
        super.setText("binds");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBinds(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBinds(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TBinds text.");
    }
}
