/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TCompatible extends Token
{
    public TCompatible()
    {
        super.setText("compatible");
    }

    public TCompatible(int line, int pos)
    {
        super.setText("compatible");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCompatible(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCompatible(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCompatible text.");
    }
}
