/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TDays extends Token
{
    public TDays()
    {
        super.setText("days");
    }

    public TDays(int line, int pos)
    {
        super.setText("days");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDays(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDays(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDays text.");
    }
}
