/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TEquivalent extends Token
{
    public TEquivalent()
    {
        super.setText("equivalent");
    }

    public TEquivalent(int line, int pos)
    {
        super.setText("equivalent");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEquivalent(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEquivalent(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEquivalent text.");
    }
}
