/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TExclude extends Token
{
    public TExclude()
    {
        super.setText("exclude");
    }

    public TExclude(int line, int pos)
    {
        super.setText("exclude");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExclude(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExclude(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExclude text.");
    }
}
