/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TFailed extends Token
{
    public TFailed()
    {
        super.setText("failed");
    }

    public TFailed(int line, int pos)
    {
        super.setText("failed");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFailed(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFailed(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFailed text.");
    }
}
