/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TFilename extends Token
{
    public TFilename()
    {
        super.setText("filename");
    }

    public TFilename(int line, int pos)
    {
        super.setText("filename");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFilename(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFilename(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFilename text.");
    }
}
