/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TGit extends Token
{
    public TGit()
    {
        super.setText("git");
    }

    public TGit(int line, int pos)
    {
        super.setText("git");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TGit(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTGit(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TGit text.");
    }
}
