/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class THours extends Token
{
    public THours()
    {
        super.setText("hours");
    }

    public THours(int line, int pos)
    {
        super.setText("hours");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THours(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHours(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THours text.");
    }
}
