/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TInputs extends Token
{
    public TInputs()
    {
        super.setText("inputs");
    }

    public TInputs(int line, int pos)
    {
        super.setText("inputs");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInputs(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInputs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInputs text.");
    }
}
