/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TNewer extends Token
{
    public TNewer()
    {
        super.setText("newer");
    }

    public TNewer(int line, int pos)
    {
        super.setText("newer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNewer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNewer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNewer text.");
    }
}
