/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TNumericKeyword extends Token
{
    public TNumericKeyword()
    {
        super.setText("numeric");
    }

    public TNumericKeyword(int line, int pos)
    {
        super.setText("numeric");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumericKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumericKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNumericKeyword text.");
    }
}
