/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TOlder extends Token
{
    public TOlder()
    {
        super.setText("older");
    }

    public TOlder(int line, int pos)
    {
        super.setText("older");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOlder(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOlder(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOlder text.");
    }
}
