/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TOutputs extends Token
{
    public TOutputs()
    {
        super.setText("outputs");
    }

    public TOutputs(int line, int pos)
    {
        super.setText("outputs");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOutputs(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOutputs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOutputs text.");
    }
}
