/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TPassword extends Token
{
    public TPassword()
    {
        super.setText("password");
    }

    public TPassword(int line, int pos)
    {
        super.setText("password");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPassword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPassword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPassword text.");
    }
}
