/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TReturns extends Token
{
    public TReturns()
    {
        super.setText("returns");
    }

    public TReturns(int line, int pos)
    {
        super.setText("returns");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReturns(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReturns(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReturns text.");
    }
}
