/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TSec extends Token
{
    public TSec()
    {
        super.setText("sec");
    }

    public TSec(int line, int pos)
    {
        super.setText("sec");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSec(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSec(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSec text.");
    }
}
