/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TShell extends Token
{
    public TShell()
    {
        super.setText("shell");
    }

    public TShell(int line, int pos)
    {
        super.setText("shell");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TShell(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTShell(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TShell text.");
    }
}
