/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TSpacesKeyword extends Token
{
    public TSpacesKeyword()
    {
        super.setText("spaces");
    }

    public TSpacesKeyword(int line, int pos)
    {
        super.setText("spaces");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSpacesKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSpacesKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSpacesKeyword text.");
    }
}
