/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TTabKeyword extends Token
{
    public TTabKeyword()
    {
        super.setText("tab");
    }

    public TTabKeyword(int line, int pos)
    {
        super.setText("tab");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTabKeyword(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTabKeyword(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTabKeyword text.");
    }
}
