/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TTask extends Token
{
    public TTask()
    {
        super.setText("task");
    }

    public TTask(int line, int pos)
    {
        super.setText("task");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTask(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTask(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTask text.");
    }
}
