/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TTested extends Token
{
    public TTested()
    {
        super.setText("tested");
    }

    public TTested(int line, int pos)
    {
        super.setText("tested");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTested(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTested(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTested text.");
    }
}
