/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TThan extends Token
{
    public TThan()
    {
        super.setText("than");
    }

    public TThan(int line, int pos)
    {
        super.setText("than");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThan(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThan(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThan text.");
    }
}
