/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TTimeout extends Token
{
    public TTimeout()
    {
        super.setText("timeout");
    }

    public TTimeout(int line, int pos)
    {
        super.setText("timeout");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTimeout(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTimeout(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTimeout text.");
    }
}
