/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TTranslation extends Token
{
    public TTranslation()
    {
        super.setText("translation");
    }

    public TTranslation(int line, int pos)
    {
        super.setText("translation");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTranslation(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTranslation(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTranslation text.");
    }
}
