/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TTranslate extends Token
{
    public TTranslate()
    {
        super.setText("translate");
    }

    public TTranslate(int line, int pos)
    {
        super.setText("translate");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTranslate(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTranslate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTranslate text.");
    }
}
