/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.node;

import scaledmarkets.dabl.analysis.*;

@SuppressWarnings("nls")
public final class TUserid extends Token
{
    public TUserid()
    {
        super.setText("userid");
    }

    public TUserid(int line, int pos)
    {
        super.setText("userid");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUserid(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUserid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUserid text.");
    }
}
