/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.parser;

import scaledmarkets.dabl.node.*;
import scaledmarkets.dabl.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTabChar(@SuppressWarnings("unused") TTabChar node)
    {
        this.index = 0;
    }

    @Override
    public void caseTNlChar(@SuppressWarnings("unused") TNlChar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTCommaChar(@SuppressWarnings("unused") TCommaChar node)
    {
        this.index = 2;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 3;
    }

    @Override
    public void caseTDash(@SuppressWarnings("unused") TDash node)
    {
        this.index = 4;
    }

    @Override
    public void caseTAsterisk(@SuppressWarnings("unused") TAsterisk node)
    {
        this.index = 5;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 6;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 7;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 8;
    }

    @Override
    public void caseTGe(@SuppressWarnings("unused") TGe node)
    {
        this.index = 9;
    }

    @Override
    public void caseTLe(@SuppressWarnings("unused") TLe node)
    {
        this.index = 10;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 11;
    }

    @Override
    public void caseTNe(@SuppressWarnings("unused") TNe node)
    {
        this.index = 12;
    }

    @Override
    public void caseTGets(@SuppressWarnings("unused") TGets node)
    {
        this.index = 13;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 14;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 15;
    }

    @Override
    public void caseTDotdot(@SuppressWarnings("unused") TDotdot node)
    {
        this.index = 16;
    }

    @Override
    public void caseTQmark(@SuppressWarnings("unused") TQmark node)
    {
        this.index = 17;
    }

    @Override
    public void caseTDef(@SuppressWarnings("unused") TDef node)
    {
        this.index = 18;
    }

    @Override
    public void caseTLeftParen(@SuppressWarnings("unused") TLeftParen node)
    {
        this.index = 19;
    }

    @Override
    public void caseTRightParen(@SuppressWarnings("unused") TRightParen node)
    {
        this.index = 20;
    }

    @Override
    public void caseTLeftCur(@SuppressWarnings("unused") TLeftCur node)
    {
        this.index = 21;
    }

    @Override
    public void caseTRightCur(@SuppressWarnings("unused") TRightCur node)
    {
        this.index = 22;
    }

    @Override
    public void caseTLeftBrack(@SuppressWarnings("unused") TLeftBrack node)
    {
        this.index = 23;
    }

    @Override
    public void caseTRightBrack(@SuppressWarnings("unused") TRightBrack node)
    {
        this.index = 24;
    }

    @Override
    public void caseTPerChar(@SuppressWarnings("unused") TPerChar node)
    {
        this.index = 25;
    }

    @Override
    public void caseTCaret(@SuppressWarnings("unused") TCaret node)
    {
        this.index = 26;
    }

    @Override
    public void caseTFrom(@SuppressWarnings("unused") TFrom node)
    {
        this.index = 27;
    }

    @Override
    public void caseTTo(@SuppressWarnings("unused") TTo node)
    {
        this.index = 28;
    }

    @Override
    public void caseTIn(@SuppressWarnings("unused") TIn node)
    {
        this.index = 29;
    }

    @Override
    public void caseTFor(@SuppressWarnings("unused") TFor node)
    {
        this.index = 30;
    }

    @Override
    public void caseTWith(@SuppressWarnings("unused") TWith node)
    {
        this.index = 31;
    }

    @Override
    public void caseTWhen(@SuppressWarnings("unused") TWhen node)
    {
        this.index = 32;
    }

    @Override
    public void caseTOn(@SuppressWarnings("unused") TOn node)
    {
        this.index = 33;
    }

    @Override
    public void caseTOf(@SuppressWarnings("unused") TOf node)
    {
        this.index = 34;
    }

    @Override
    public void caseTThan(@SuppressWarnings("unused") TThan node)
    {
        this.index = 35;
    }

    @Override
    public void caseTNamespace(@SuppressWarnings("unused") TNamespace node)
    {
        this.index = 36;
    }

    @Override
    public void caseTImport(@SuppressWarnings("unused") TImport node)
    {
        this.index = 37;
    }

    @Override
    public void caseTTabKeyword(@SuppressWarnings("unused") TTabKeyword node)
    {
        this.index = 38;
    }

    @Override
    public void caseTEquivalent(@SuppressWarnings("unused") TEquivalent node)
    {
        this.index = 39;
    }

    @Override
    public void caseTSpacesKeyword(@SuppressWarnings("unused") TSpacesKeyword node)
    {
        this.index = 40;
    }

    @Override
    public void caseTArtifact(@SuppressWarnings("unused") TArtifact node)
    {
        this.index = 41;
    }

    @Override
    public void caseTTask(@SuppressWarnings("unused") TTask node)
    {
        this.index = 42;
    }

    @Override
    public void caseTPublic(@SuppressWarnings("unused") TPublic node)
    {
        this.index = 43;
    }

    @Override
    public void caseTRepo(@SuppressWarnings("unused") TRepo node)
    {
        this.index = 44;
    }

    @Override
    public void caseTType(@SuppressWarnings("unused") TType node)
    {
        this.index = 45;
    }

    @Override
    public void caseTGit(@SuppressWarnings("unused") TGit node)
    {
        this.index = 46;
    }

    @Override
    public void caseTFiles(@SuppressWarnings("unused") TFiles node)
    {
        this.index = 47;
    }

    @Override
    public void caseTShell(@SuppressWarnings("unused") TShell node)
    {
        this.index = 48;
    }

    @Override
    public void caseTTranslation(@SuppressWarnings("unused") TTranslation node)
    {
        this.index = 49;
    }

    @Override
    public void caseTTranslate(@SuppressWarnings("unused") TTranslate node)
    {
        this.index = 50;
    }

    @Override
    public void caseTFilename(@SuppressWarnings("unused") TFilename node)
    {
        this.index = 51;
    }

    @Override
    public void caseTPrefer(@SuppressWarnings("unused") TPrefer node)
    {
        this.index = 52;
    }

    @Override
    public void caseTLatest(@SuppressWarnings("unused") TLatest node)
    {
        this.index = 53;
    }

    @Override
    public void caseTAssume(@SuppressWarnings("unused") TAssume node)
    {
        this.index = 54;
    }

    @Override
    public void caseTCompatible(@SuppressWarnings("unused") TCompatible node)
    {
        this.index = 55;
    }

    @Override
    public void caseTTested(@SuppressWarnings("unused") TTested node)
    {
        this.index = 56;
    }

    @Override
    public void caseTFunction(@SuppressWarnings("unused") TFunction node)
    {
        this.index = 57;
    }

    @Override
    public void caseTBinds(@SuppressWarnings("unused") TBinds node)
    {
        this.index = 58;
    }

    @Override
    public void caseTMethod(@SuppressWarnings("unused") TMethod node)
    {
        this.index = 59;
    }

    @Override
    public void caseTReturns(@SuppressWarnings("unused") TReturns node)
    {
        this.index = 60;
    }

    @Override
    public void caseTSucceeded(@SuppressWarnings("unused") TSucceeded node)
    {
        this.index = 61;
    }

    @Override
    public void caseTFailed(@SuppressWarnings("unused") TFailed node)
    {
        this.index = 62;
    }

    @Override
    public void caseTNewer(@SuppressWarnings("unused") TNewer node)
    {
        this.index = 63;
    }

    @Override
    public void caseTOlder(@SuppressWarnings("unused") TOlder node)
    {
        this.index = 64;
    }

    @Override
    public void caseTInputs(@SuppressWarnings("unused") TInputs node)
    {
        this.index = 65;
    }

    @Override
    public void caseTOutputs(@SuppressWarnings("unused") TOutputs node)
    {
        this.index = 66;
    }

    @Override
    public void caseTPathKeyword(@SuppressWarnings("unused") TPathKeyword node)
    {
        this.index = 67;
    }

    @Override
    public void caseTScheme(@SuppressWarnings("unused") TScheme node)
    {
        this.index = 68;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 69;
    }

    @Override
    public void caseTEnd(@SuppressWarnings("unused") TEnd node)
    {
        this.index = 70;
    }

    @Override
    public void caseTError(@SuppressWarnings("unused") TError node)
    {
        this.index = 71;
    }

    @Override
    public void caseTStringKeyword(@SuppressWarnings("unused") TStringKeyword node)
    {
        this.index = 72;
    }

    @Override
    public void caseTNumericKeyword(@SuppressWarnings("unused") TNumericKeyword node)
    {
        this.index = 73;
    }

    @Override
    public void caseTLogicalKeyword(@SuppressWarnings("unused") TLogicalKeyword node)
    {
        this.index = 74;
    }

    @Override
    public void caseTNotKeyword(@SuppressWarnings("unused") TNotKeyword node)
    {
        this.index = 75;
    }

    @Override
    public void caseTAndKeyword(@SuppressWarnings("unused") TAndKeyword node)
    {
        this.index = 76;
    }

    @Override
    public void caseTOrKeyword(@SuppressWarnings("unused") TOrKeyword node)
    {
        this.index = 77;
    }

    @Override
    public void caseTInclude(@SuppressWarnings("unused") TInclude node)
    {
        this.index = 78;
    }

    @Override
    public void caseTExclude(@SuppressWarnings("unused") TExclude node)
    {
        this.index = 79;
    }

    @Override
    public void caseTTrueKeyword(@SuppressWarnings("unused") TTrueKeyword node)
    {
        this.index = 80;
    }

    @Override
    public void caseTFalseKeyword(@SuppressWarnings("unused") TFalseKeyword node)
    {
        this.index = 81;
    }

    @Override
    public void caseTUserid(@SuppressWarnings("unused") TUserid node)
    {
        this.index = 82;
    }

    @Override
    public void caseTPassword(@SuppressWarnings("unused") TPassword node)
    {
        this.index = 83;
    }

    @Override
    public void caseTNew(@SuppressWarnings("unused") TNew node)
    {
        this.index = 84;
    }

    @Override
    public void caseTLocal(@SuppressWarnings("unused") TLocal node)
    {
        this.index = 85;
    }

    @Override
    public void caseTOpen(@SuppressWarnings("unused") TOpen node)
    {
        this.index = 86;
    }

    @Override
    public void caseTArrayKeyword(@SuppressWarnings("unused") TArrayKeyword node)
    {
        this.index = 87;
    }

    @Override
    public void caseTTimeout(@SuppressWarnings("unused") TTimeout node)
    {
        this.index = 88;
    }

    @Override
    public void caseTMs(@SuppressWarnings("unused") TMs node)
    {
        this.index = 89;
    }

    @Override
    public void caseTSec(@SuppressWarnings("unused") TSec node)
    {
        this.index = 90;
    }

    @Override
    public void caseTMin(@SuppressWarnings("unused") TMin node)
    {
        this.index = 91;
    }

    @Override
    public void caseTHours(@SuppressWarnings("unused") THours node)
    {
        this.index = 92;
    }

    @Override
    public void caseTDays(@SuppressWarnings("unused") TDays node)
    {
        this.index = 93;
    }

    @Override
    public void caseTUse(@SuppressWarnings("unused") TUse node)
    {
        this.index = 94;
    }

    @Override
    public void caseTWholeNumber(@SuppressWarnings("unused") TWholeNumber node)
    {
        this.index = 95;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 96;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 97;
    }

    @Override
    public void caseTString2(@SuppressWarnings("unused") TString2 node)
    {
        this.index = 98;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 99;
    }
}
