/* This file was generated by SableCC (http://www.sablecc.org/). */

package scaledmarkets.dabl.lexer;

import java.io.*;
import scaledmarkets.dabl.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 60:
                        {
                            @SuppressWarnings("hiding") Token token = new60(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 61:
                        {
                            @SuppressWarnings("hiding") Token token = new61(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 62:
                        {
                            @SuppressWarnings("hiding") Token token = new62(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 63:
                        {
                            @SuppressWarnings("hiding") Token token = new63(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 64:
                        {
                            @SuppressWarnings("hiding") Token token = new64(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 65:
                        {
                            @SuppressWarnings("hiding") Token token = new65(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 66:
                        {
                            @SuppressWarnings("hiding") Token token = new66(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 67:
                        {
                            @SuppressWarnings("hiding") Token token = new67(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 68:
                        {
                            @SuppressWarnings("hiding") Token token = new68(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 69:
                        {
                            @SuppressWarnings("hiding") Token token = new69(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 70:
                        {
                            @SuppressWarnings("hiding") Token token = new70(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 71:
                        {
                            @SuppressWarnings("hiding") Token token = new71(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 72:
                        {
                            @SuppressWarnings("hiding") Token token = new72(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 73:
                        {
                            @SuppressWarnings("hiding") Token token = new73(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 74:
                        {
                            @SuppressWarnings("hiding") Token token = new74(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 75:
                        {
                            @SuppressWarnings("hiding") Token token = new75(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 76:
                        {
                            @SuppressWarnings("hiding") Token token = new76(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 77:
                        {
                            @SuppressWarnings("hiding") Token token = new77(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 78:
                        {
                            @SuppressWarnings("hiding") Token token = new78(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 79:
                        {
                            @SuppressWarnings("hiding") Token token = new79(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 80:
                        {
                            @SuppressWarnings("hiding") Token token = new80(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 81:
                        {
                            @SuppressWarnings("hiding") Token token = new81(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 82:
                        {
                            @SuppressWarnings("hiding") Token token = new82(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 83:
                        {
                            @SuppressWarnings("hiding") Token token = new83(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 84:
                        {
                            @SuppressWarnings("hiding") Token token = new84(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 85:
                        {
                            @SuppressWarnings("hiding") Token token = new85(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 86:
                        {
                            @SuppressWarnings("hiding") Token token = new86(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 87:
                        {
                            @SuppressWarnings("hiding") Token token = new87(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 88:
                        {
                            @SuppressWarnings("hiding") Token token = new88(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 89:
                        {
                            @SuppressWarnings("hiding") Token token = new89(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 90:
                        {
                            @SuppressWarnings("hiding") Token token = new90(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 91:
                        {
                            @SuppressWarnings("hiding") Token token = new91(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 92:
                        {
                            @SuppressWarnings("hiding") Token token = new92(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 93:
                        {
                            @SuppressWarnings("hiding") Token token = new93(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 94:
                        {
                            @SuppressWarnings("hiding") Token token = new94(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 95:
                        {
                            @SuppressWarnings("hiding") Token token = new95(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 96:
                        {
                            @SuppressWarnings("hiding") Token token = new96(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 97:
                        {
                            @SuppressWarnings("hiding") Token token = new97(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 98:
                        {
                            @SuppressWarnings("hiding") Token token = new98(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 99:
                        {
                            @SuppressWarnings("hiding") Token token = new99(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 100:
                        {
                            @SuppressWarnings("hiding") Token token = new100(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 101:
                        {
                            @SuppressWarnings("hiding") Token token = new101(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 102:
                        {
                            @SuppressWarnings("hiding") Token token = new102(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 103:
                        {
                            @SuppressWarnings("hiding") Token token = new103(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTabChar(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNlChar(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCommaChar(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDash(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAsterisk(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGt(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLt(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGe(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLe(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEq(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNe(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGets(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDotdot(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TQmark(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDef(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftParen(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightParen(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftCur(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightCur(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeftBrack(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRightBrack(line, pos); }
    Token new25(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPerChar(text, line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaret(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFrom(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTo(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIn(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFor(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWith(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhen(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOn(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOf(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThan(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNamespace(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TImport(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTabKeyword(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEquivalent(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSpacesKeyword(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArtifact(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTask(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPublic(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepo(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TType(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGit(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFiles(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TShell(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTranslation(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTranslate(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFilename(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrefer(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLatest(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAssume(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCompatible(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTested(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFunction(line, pos); }
    Token new58(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBinds(line, pos); }
    Token new59(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMethod(line, pos); }
    Token new60(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturns(line, pos); }
    Token new61(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSucceeded(line, pos); }
    Token new62(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFailed(line, pos); }
    Token new63(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNewer(line, pos); }
    Token new64(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOlder(line, pos); }
    Token new65(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInputs(line, pos); }
    Token new66(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOutputs(line, pos); }
    Token new67(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPathKeyword(line, pos); }
    Token new68(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TScheme(line, pos); }
    Token new69(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new70(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnd(line, pos); }
    Token new71(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TError(line, pos); }
    Token new72(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringKeyword(line, pos); }
    Token new73(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumericKeyword(line, pos); }
    Token new74(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLogicalKeyword(line, pos); }
    Token new75(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotKeyword(line, pos); }
    Token new76(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAndKeyword(line, pos); }
    Token new77(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOrKeyword(line, pos); }
    Token new78(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInclude(line, pos); }
    Token new79(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TExclude(line, pos); }
    Token new80(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrueKeyword(line, pos); }
    Token new81(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalseKeyword(line, pos); }
    Token new82(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUserid(line, pos); }
    Token new83(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPassword(line, pos); }
    Token new84(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNew(line, pos); }
    Token new85(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLocal(line, pos); }
    Token new86(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOpen(line, pos); }
    Token new87(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TArrayKeyword(line, pos); }
    Token new88(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTimeout(line, pos); }
    Token new89(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMs(line, pos); }
    Token new90(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSec(line, pos); }
    Token new91(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMin(line, pos); }
    Token new92(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THours(line, pos); }
    Token new93(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDays(line, pos); }
    Token new94(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TUse(line, pos); }
    Token new95(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWholeNumber(text, line, pos); }
    Token new96(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhitespace(text, line, pos); }
    Token new97(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new98(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new99(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString2(text, line, pos); }
    Token new100(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlashslashcomment(text, line, pos); }
    Token new101(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlashslashslashcomment(text, line, pos); }
    Token new102(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlashstarcomment(text, line, pos); }
    Token new103(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSlashslashstarcomment(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {34, 34, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 13}, {47, 47, 14}, {48, 57, 15}, {58, 58, 16}, {59, 59, 17}, {60, 60, 18}, {61, 61, 19}, {62, 62, 20}, {63, 63, 21}, {65, 90, 22}, {91, 91, 23}, {93, 93, 24}, {94, 94, 25}, {95, 95, 26}, {97, 97, 27}, {98, 98, 28}, {99, 99, 29}, {100, 100, 30}, {101, 101, 31}, {102, 102, 32}, {103, 103, 33}, {104, 104, 34}, {105, 105, 35}, {106, 107, 36}, {108, 108, 37}, {109, 109, 38}, {110, 110, 39}, {111, 111, 40}, {112, 112, 41}, {113, 113, 36}, {114, 114, 42}, {115, 115, 43}, {116, 116, 44}, {117, 117, 45}, {118, 118, 36}, {119, 119, 46}, {120, 122, 36}, {123, 123, 47}, {125, 125, 48}, },
            {{9, 9, 49}, {10, 10, 50}, {13, 32, -2}, },
            {{9, 32, -3}, },
            {{9, 32, -3}, },
            {{9, 32, -3}, },
            {{61, 61, 51}, },
            {{0, 33, 52}, {34, 34, 53}, {35, 65535, 52}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{46, 46, 54}, },
            {{42, 42, 55}, {47, 47, 56}, },
            {{48, 57, 15}, },
            {},
            {},
            {{45, 45, 57}, {61, 61, 58}, },
            {},
            {{61, 61, 59}, },
            {},
            {{48, 57, 60}, {65, 90, 61}, {95, 95, 62}, {97, 122, 63}, },
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 109, 63}, {110, 110, 64}, {111, 113, 63}, {114, 114, 65}, {115, 115, 66}, {116, 122, 63}, },
            {{48, 95, -24}, {97, 104, 63}, {105, 105, 67}, {106, 122, 63}, },
            {{48, 95, -24}, {97, 110, 63}, {111, 111, 68}, {112, 122, 63}, },
            {{48, 95, -24}, {97, 97, 69}, {98, 100, 63}, {101, 101, 70}, {102, 122, 63}, },
            {{48, 109, -29}, {110, 110, 71}, {111, 112, 63}, {113, 113, 72}, {114, 114, 73}, {115, 119, 63}, {120, 120, 74}, {121, 122, 63}, },
            {{48, 95, -24}, {97, 97, 75}, {98, 104, 63}, {105, 105, 76}, {106, 110, 63}, {111, 111, 77}, {112, 113, 63}, {114, 114, 78}, {115, 116, 63}, {117, 117, 79}, {118, 122, 63}, },
            {{48, 104, -30}, {105, 105, 80}, {106, 122, 63}, },
            {{48, 110, -31}, {111, 111, 81}, {112, 122, 63}, },
            {{48, 95, -24}, {97, 101, 63}, {102, 102, 82}, {103, 108, 63}, {109, 109, 83}, {110, 110, 84}, {111, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 85}, {98, 110, 63}, {111, 111, 86}, {112, 122, 63}, },
            {{48, 95, -24}, {97, 100, 63}, {101, 101, 87}, {102, 104, 63}, {105, 105, 88}, {106, 114, 63}, {115, 115, 89}, {116, 122, 63}, },
            {{48, 95, -24}, {97, 97, 90}, {98, 100, 63}, {101, 101, 91}, {102, 110, 63}, {111, 111, 92}, {112, 116, 63}, {117, 117, 93}, {118, 122, 63}, },
            {{48, 101, -37}, {102, 102, 94}, {103, 107, 63}, {108, 108, 95}, {109, 109, 63}, {110, 110, 96}, {111, 111, 63}, {112, 112, 97}, {113, 113, 63}, {114, 114, 98}, {115, 116, 63}, {117, 117, 99}, {118, 122, 63}, },
            {{48, 95, -24}, {97, 97, 100}, {98, 113, 63}, {114, 114, 101}, {115, 116, 63}, {117, 117, 102}, {118, 122, 63}, },
            {{48, 100, -40}, {101, 101, 103}, {102, 122, 63}, },
            {{48, 95, -24}, {97, 98, 63}, {99, 99, 104}, {100, 100, 63}, {101, 101, 105}, {102, 103, 63}, {104, 104, 106}, {105, 111, 63}, {112, 112, 107}, {113, 115, 63}, {116, 116, 108}, {117, 117, 109}, {118, 122, 63}, },
            {{48, 95, -24}, {97, 97, 110}, {98, 100, 63}, {101, 101, 111}, {102, 103, 63}, {104, 104, 112}, {105, 105, 113}, {106, 110, 63}, {111, 111, 114}, {112, 113, 63}, {114, 114, 115}, {115, 120, 63}, {121, 121, 116}, {122, 122, 63}, },
            {{48, 95, -24}, {97, 114, 63}, {115, 115, 117}, {116, 122, 63}, },
            {{48, 95, -24}, {97, 103, 63}, {104, 104, 118}, {105, 105, 119}, {106, 122, 63}, },
            {},
            {},
            {{9, 32, -3}, },
            {{9, 32, -3}, },
            {},
            {{0, 33, 52}, {34, 34, 120}, {35, 65535, 52}, },
            {{34, 34, 121}, },
            {},
            {{0, 41, 122}, {42, 42, 123}, {43, 65535, 122}, },
            {{0, 9, 124}, {10, 10, 125}, {11, 41, 124}, {42, 42, 126}, {43, 46, 124}, {47, 47, 127}, {48, 65535, 124}, },
            {},
            {},
            {},
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 99, 63}, {100, 100, 128}, {101, 122, 63}, },
            {{48, 95, -24}, {97, 113, 63}, {114, 114, 129}, {115, 115, 63}, {116, 116, 130}, {117, 122, 63}, },
            {{48, 114, -47}, {115, 115, 131}, {116, 122, 63}, },
            {{48, 109, -29}, {110, 110, 132}, {111, 122, 63}, },
            {{48, 95, -24}, {97, 108, 63}, {109, 109, 133}, {110, 122, 63}, },
            {{48, 95, -24}, {97, 120, 63}, {121, 121, 134}, {122, 122, 63}, },
            {{48, 101, -37}, {102, 102, 135}, {103, 122, 63}, },
            {{48, 99, -66}, {100, 100, 136}, {101, 122, 63}, },
            {{48, 95, -24}, {97, 116, 63}, {117, 117, 137}, {118, 122, 63}, },
            {{48, 113, -67}, {114, 114, 138}, {115, 122, 63}, },
            {{48, 98, -45}, {99, 99, 139}, {100, 122, 63}, },
            {{48, 104, -30}, {105, 105, 140}, {106, 107, 63}, {108, 108, 141}, {109, 122, 63}, },
            {{48, 95, -24}, {97, 107, 63}, {108, 108, 142}, {109, 122, 63}, },
            {{48, 113, -67}, {114, 114, 143}, {115, 122, 63}, },
            {{48, 110, -31}, {111, 111, 144}, {112, 122, 63}, },
            {{48, 109, -29}, {110, 110, 145}, {111, 122, 63}, },
            {{48, 95, -24}, {97, 115, 63}, {116, 116, 146}, {117, 122, 63}, },
            {{48, 116, -74}, {117, 117, 147}, {118, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 111, 63}, {112, 112, 148}, {113, 122, 63}, },
            {{48, 98, -45}, {99, 99, 149}, {100, 111, 63}, {112, 112, 150}, {113, 122, 63}, },
            {{48, 115, -82}, {116, 116, 151}, {117, 122, 63}, },
            {{48, 98, -45}, {99, 99, 152}, {100, 102, 63}, {103, 103, 153}, {104, 122, 63}, },
            {{48, 115, -82}, {116, 116, 154}, {117, 122, 63}, },
            {{48, 109, -29}, {110, 110, 155}, {111, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 108, -70}, {109, 109, 156}, {110, 122, 63}, },
            {{48, 95, -24}, {97, 118, 63}, {119, 119, 157}, {120, 122, 63}, },
            {{48, 115, -82}, {116, 116, 158}, {117, 122, 63}, },
            {{48, 108, -70}, {109, 109, 159}, {110, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 99, -66}, {100, 100, 160}, {101, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 161}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 162}, {117, 122, 63}, },
            {{48, 114, -47}, {115, 115, 163}, {116, 116, 164}, {117, 122, 63}, },
            {{48, 100, -40}, {101, 101, 165}, {102, 122, 63}, },
            {{48, 95, -24}, {97, 97, 63}, {98, 98, 166}, {99, 122, 63}, },
            {{48, 111, -85}, {112, 112, 167}, {113, 115, 63}, {116, 116, 168}, {117, 122, 63}, },
            {{48, 103, -48}, {104, 104, 169}, {105, 122, 63}, },
            {{48, 98, -45}, {99, 99, 170}, {100, 122, 63}, },
            {{48, 100, -40}, {101, 101, 171}, {102, 122, 63}, },
            {{48, 95, -24}, {97, 97, 172}, {98, 122, 63}, },
            {{48, 113, -67}, {114, 114, 173}, {115, 122, 63}, },
            {{48, 98, -45}, {99, 99, 174}, {100, 122, 63}, },
            {{48, 97, -104}, {98, 98, 175}, {99, 114, 63}, {115, 115, 176}, {116, 122, 63}, },
            {{48, 114, -47}, {115, 115, 177}, {116, 122, 63}, },
            {{48, 95, -24}, {97, 97, 178}, {98, 122, 63}, },
            {{48, 108, -70}, {109, 109, 179}, {110, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 180}, {98, 116, 63}, {117, 117, 181}, {118, 122, 63}, },
            {{48, 111, -85}, {112, 112, 182}, {113, 122, 63}, },
            {{48, 100, -40}, {101, 101, 183}, {102, 122, 63}, },
            {{48, 100, -40}, {101, 101, 184}, {102, 122, 63}, },
            {{48, 115, -82}, {116, 116, 185}, {117, 122, 63}, },
            {},
            {{0, 33, 186}, {34, 34, 187}, {35, 65535, 186}, },
            {{0, 65535, -57}, },
            {{0, 42, -57}, {43, 46, 122}, {47, 47, 188}, {48, 65535, 122}, },
            {{0, 10, -58}, {11, 65535, 124}, },
            {},
            {{0, 9, 189}, {10, 10, 190}, {11, 41, 189}, {42, 42, 191}, {43, 65535, 189}, },
            {{0, 9, 192}, {10, 10, 193}, {11, 65535, 192}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 194}, {98, 122, 63}, },
            {{48, 104, -30}, {105, 105, 195}, {106, 122, 63}, },
            {{48, 116, -74}, {117, 117, 196}, {118, 122, 63}, },
            {{48, 99, -66}, {100, 100, 197}, {101, 122, 63}, },
            {{48, 111, -85}, {112, 112, 198}, {113, 122, 63}, },
            {{48, 114, -47}, {115, 115, 199}, {116, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 104, -30}, {105, 105, 200}, {106, 122, 63}, },
            {{48, 110, -31}, {111, 111, 201}, {112, 122, 63}, },
            {{48, 107, -78}, {108, 108, 202}, {109, 122, 63}, },
            {{48, 107, -78}, {108, 108, 203}, {109, 122, 63}, },
            {{48, 114, -47}, {115, 115, 204}, {116, 122, 63}, },
            {{48, 100, -40}, {101, 101, 205}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 108, -70}, {109, 109, 206}, {110, 122, 63}, },
            {{48, 98, -45}, {99, 99, 207}, {100, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 113, -67}, {114, 114, 208}, {115, 122, 63}, },
            {{48, 110, -31}, {111, 111, 209}, {112, 122, 63}, },
            {{48, 107, -78}, {108, 108, 210}, {109, 122, 63}, },
            {{48, 116, -74}, {117, 117, 211}, {118, 122, 63}, },
            {{48, 100, -40}, {101, 101, 212}, {102, 122, 63}, },
            {{48, 95, -24}, {97, 97, 213}, {98, 122, 63}, },
            {{48, 104, -30}, {105, 105, 214}, {106, 122, 63}, },
            {{48, 103, -48}, {104, 104, 215}, {105, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 216}, {102, 122, 63}, },
            {{48, 100, -40}, {101, 101, 217}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 218}, {102, 122, 63}, },
            {{48, 100, -40}, {101, 101, 219}, {102, 122, 63}, },
            {{48, 109, -29}, {110, 110, 220}, {111, 122, 63}, },
            {{48, 111, -85}, {112, 112, 221}, {113, 122, 63}, },
            {{48, 114, -47}, {115, 115, 222}, {116, 122, 63}, },
            {{48, 103, -48}, {104, 104, 223}, {105, 122, 63}, },
            {{48, 101, -37}, {102, 102, 224}, {103, 122, 63}, },
            {{48, 107, -78}, {108, 108, 225}, {109, 122, 63}, },
            {{48, 110, -31}, {111, 111, 226}, {112, 122, 63}, },
            {{48, 116, -74}, {117, 117, 227}, {118, 122, 63}, },
            {{48, 100, -40}, {101, 101, 228}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 107, -78}, {108, 108, 229}, {109, 122, 63}, },
            {{48, 98, -45}, {99, 99, 230}, {100, 122, 63}, },
            {{48, 104, -30}, {105, 105, 231}, {106, 122, 63}, },
            {{48, 98, -45}, {99, 99, 232}, {100, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 106, 63}, {107, 107, 233}, {108, 122, 63}, },
            {{48, 115, -82}, {116, 116, 234}, {117, 122, 63}, },
            {{48, 109, -29}, {110, 110, 235}, {111, 122, 63}, },
            {{48, 100, -40}, {101, 101, 236}, {102, 122, 63}, },
            {{48, 109, -29}, {110, 110, 237}, {111, 122, 63}, },
            {{48, 100, -40}, {101, 101, 238}, {102, 122, 63}, },
            {{48, 100, -40}, {101, 101, 239}, {102, 122, 63}, },
            {{48, 113, -67}, {114, 114, 240}, {115, 122, 63}, },
            {{48, 109, -29}, {110, 110, 241}, {111, 122, 63}, },
            {{48, 103, -48}, {104, 104, 242}, {105, 122, 63}, },
            {{0, 65535, -123}, },
            {{0, 33, 186}, {34, 34, 243}, {35, 65535, 186}, },
            {{0, 65535, -57}, },
            {{0, 65535, -128}, },
            {{0, 41, 244}, {42, 42, 245}, {43, 65535, 244}, },
            {{0, 42, -128}, {43, 46, 189}, {47, 47, 246}, {48, 65535, 189}, },
            {{0, 65535, -129}, },
            {},
            {{48, 120, -71}, {121, 121, 247}, {122, 122, 63}, },
            {{48, 101, -37}, {102, 102, 248}, {103, 122, 63}, },
            {{48, 108, -70}, {109, 109, 249}, {110, 122, 63}, },
            {{48, 114, -47}, {115, 115, 250}, {116, 122, 63}, },
            {{48, 95, -24}, {97, 97, 251}, {98, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 117, 63}, {118, 118, 252}, {119, 122, 63}, },
            {{48, 113, -67}, {114, 114, 253}, {115, 122, 63}, },
            {{48, 116, -74}, {117, 117, 254}, {118, 122, 63}, },
            {{48, 100, -40}, {101, 101, 255}, {102, 122, 63}, },
            {{48, 100, -40}, {101, 101, 256}, {102, 122, 63}, },
            {{48, 109, -29}, {110, 110, 257}, {111, 114, 63}, {115, 115, 258}, {116, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 259}, {117, 122, 63}, },
            {{48, 114, -47}, {115, 115, 260}, {116, 122, 63}, },
            {{48, 113, -67}, {114, 114, 261}, {115, 122, 63}, },
            {{48, 116, -74}, {117, 117, 262}, {118, 122, 63}, },
            {{48, 115, -82}, {116, 116, 263}, {117, 122, 63}, },
            {{48, 114, -47}, {115, 115, 264}, {116, 122, 63}, },
            {{48, 107, -78}, {108, 108, 265}, {109, 122, 63}, },
            {{48, 98, -45}, {99, 99, 266}, {100, 122, 63}, },
            {{48, 110, -31}, {111, 111, 267}, {112, 122, 63}, },
            {{48, 114, -47}, {115, 115, 268}, {116, 122, 63}, },
            {{48, 113, -67}, {114, 114, 269}, {115, 122, 63}, },
            {{48, 113, -67}, {114, 114, 270}, {115, 122, 63}, },
            {{48, 113, -67}, {114, 114, 271}, {115, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 116, -74}, {117, 117, 272}, {118, 122, 63}, },
            {{48, 118, -93}, {119, 119, 273}, {120, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 274}, {102, 122, 63}, },
            {{48, 104, -30}, {105, 105, 275}, {106, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 113, -67}, {114, 114, 276}, {115, 122, 63}, },
            {{48, 108, -70}, {109, 109, 277}, {110, 122, 63}, },
            {{48, 107, -78}, {108, 108, 278}, {109, 122, 63}, },
            {{48, 100, -40}, {101, 101, 279}, {102, 122, 63}, },
            {{48, 109, -29}, {110, 110, 280}, {111, 122, 63}, },
            {{48, 100, -40}, {101, 101, 281}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 282}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 110, -31}, {111, 111, 283}, {112, 122, 63}, },
            {{48, 114, -47}, {115, 115, 284}, {116, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 104, -30}, {105, 105, 285}, {106, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{0, 33, 186}, {34, 34, 286}, {35, 65535, 186}, },
            {{0, 65535, -192}, },
            {{0, 42, -192}, {43, 46, 244}, {47, 47, 287}, {48, 65535, 244}, },
            {{0, 46, -193}, {47, 47, 288}, {48, 65535, 189}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 289}, {98, 122, 63}, },
            {{48, 100, -40}, {101, 101, 290}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 291}, {117, 122, 63}, },
            {{48, 95, -24}, {97, 97, 292}, {98, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 99, -66}, {100, 100, 293}, {101, 122, 63}, },
            {{48, 99, -66}, {100, 100, 294}, {101, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 295}, {98, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 104, -30}, {105, 105, 296}, {106, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 297}, {117, 122, 63}, },
            {{48, 99, -66}, {100, 100, 298}, {101, 122, 63}, },
            {{48, 114, -47}, {115, 115, 299}, {116, 122, 63}, },
            {{48, 115, -82}, {116, 116, 300}, {117, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 301}, {98, 122, 63}, },
            {{48, 99, -66}, {100, 100, 302}, {101, 122, 63}, },
            {{48, 111, -85}, {112, 112, 303}, {113, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 104, -30}, {105, 105, 304}, {106, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 305}, {117, 122, 63}, },
            {{48, 110, -31}, {111, 111, 306}, {112, 122, 63}, },
            {{48, 113, -67}, {114, 114, 307}, {115, 122, 63}, },
            {{48, 98, -45}, {99, 99, 308}, {100, 122, 63}, },
            {{48, 109, -29}, {110, 110, 309}, {111, 122, 63}, },
            {{48, 100, -40}, {101, 101, 310}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 114, -47}, {115, 115, 311}, {116, 122, 63}, },
            {{48, 95, -24}, {97, 102, 63}, {103, 103, 312}, {104, 122, 63}, },
            {{48, 100, -40}, {101, 101, 313}, {102, 122, 63}, },
            {{48, 99, -66}, {100, 100, 314}, {101, 122, 63}, },
            {{48, 116, -74}, {117, 117, 315}, {118, 122, 63}, },
            {{48, 107, -78}, {108, 108, 316}, {109, 122, 63}, },
            {{48, 99, -66}, {100, 100, 317}, {101, 122, 63}, },
            {{0, 65535, -245}, },
            {{0, 46, -247}, {47, 47, 318}, {48, 65535, 244}, },
            {{0, 65535, -128}, },
            {{48, 98, -45}, {99, 99, 319}, {100, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 104, -30}, {105, 105, 320}, {106, 122, 63}, },
            {{48, 107, -78}, {108, 108, 321}, {109, 122, 63}, },
            {{48, 100, -40}, {101, 101, 322}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 108, -70}, {109, 109, 323}, {110, 122, 63}, },
            {{48, 110, -31}, {111, 111, 324}, {112, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 325}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 107, -78}, {108, 108, 326}, {109, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 95, -24}, {97, 97, 327}, {98, 122, 63}, },
            {{48, 98, -45}, {99, 99, 328}, {100, 122, 63}, },
            {{48, 114, -47}, {115, 115, 329}, {116, 122, 63}, },
            {{48, 113, -67}, {114, 114, 330}, {115, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 114, -47}, {115, 115, 331}, {116, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 99, -66}, {100, 100, 332}, {101, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 333}, {117, 122, 63}, },
            {{48, 95, -24}, {97, 97, 334}, {98, 122, 63}, },
            {{48, 122, -24}, },
            {{0, 65535, -192}, },
            {{48, 115, -82}, {116, 116, 335}, {117, 122, 63}, },
            {{48, 97, -104}, {98, 98, 336}, {99, 122, 63}, },
            {{48, 100, -40}, {101, 101, 337}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 338}, {102, 122, 63}, },
            {{48, 109, -29}, {110, 110, 339}, {111, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 98, -45}, {99, 99, 340}, {100, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 99, -66}, {100, 100, 341}, {101, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 342}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 115, -82}, {116, 116, 343}, {117, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 107, -78}, {108, 108, 344}, {109, 122, 63}, },
            {{48, 109, -29}, {110, 110, 345}, {111, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 100, -40}, {101, 101, 346}, {102, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 99, -66}, {100, 100, 347}, {101, 122, 63}, },
            {{48, 100, -40}, {101, 101, 348}, {102, 104, 63}, {105, 105, 349}, {106, 122, 63}, },
            {{48, 100, -40}, {101, 101, 350}, {102, 122, 63}, },
            {{48, 115, -82}, {116, 116, 351}, {117, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 110, -31}, {111, 111, 352}, {112, 122, 63}, },
            {{48, 122, -24}, },
            {{48, 122, -24}, },
            {{48, 109, -29}, {110, 110, 353}, {111, 122, 63}, },
            {{48, 122, -24}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 0, 1, 96, 96, -1, -1, 19, 20, 5, 3, 2, 4, 25, 6, 95, 14, 15, 8, 11, 7, 17, -1, 23, 24, 26, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 21, 22, 96, 96, 12, -1, 98, 16, -1, -1, 13, 10, 9, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 69, 97, 29, 97, 97, 97, 97, 89, 97, 97, 97, 97, 34, 97, 33, 97, 77, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 28, 97, 97, 97, 97, 97, 98, -1, -1, -1, -1, 100, -1, -1, 76, 97, 97, 97, 97, 97, 97, 18, 70, 97, 97, 97, 97, 97, 97, 30, 97, 97, 46, 97, 97, 97, 97, 97, 97, 97, 97, 91, 97, 84, 75, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 90, 97, 97, 97, 97, 38, 97, 97, 97, 97, 97, 97, 97, 94, 97, 97, -1, -1, 102, -1, 100, -1, -1, 100, 97, 97, 97, 97, 97, 93, 97, 97, 97, 97, 97, 97, 27, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 86, 97, 97, 67, 97, 97, 44, 97, 97, 97, 97, 97, 97, 42, 97, 35, 97, 97, 80, 45, 97, 32, 31, -1, -1, -1, -1, 87, 97, 97, 58, 97, 97, 71, 97, 97, 81, 97, 47, 97, 92, 97, 97, 97, 97, 85, 97, 97, 97, 63, 97, 64, 97, 97, 97, 97, 97, 97, 48, 97, 97, 97, 97, 97, 97, 97, 99, -1, 103, 97, 54, 97, 97, 97, 62, 97, 97, 37, 97, 65, 53, 97, 59, 97, 97, 97, 97, 52, 43, 97, 68, 40, 72, 97, 56, 97, 97, 82, 103, 97, 97, 97, 79, 97, 97, 78, 74, 97, 73, 66, 97, 60, 97, 88, 97, 41, 97, 97, 51, 57, 97, 83, 97, 97, 97, 97, 36, 61, 50, 97, 55, 39, 97, 49, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
